image: ubuntu/focal
packages:
  - binutils
  - curl
  - build-essential
  - git
sources:
  - https://git.sr.ht/~metasyn/memex
tasks:
  - build: |
      curl -LO  https://nim-lang.org/choosenim/init.sh
      chmod +x init.sh
      ./init.sh -y stable
      PATH=${PATH}:~/.nimble/bin
      cd memex
      nimble install -y
      ./memex build
