image: ubuntu/focal
packages:
  - binutils
  - curl
  - build-essential
  - git
  - rsync
sources:
  - https://git.sr.ht/~metasyn/memex
secrets:
  - b336eab6-3f41-4b59-99ba-9132cadc232f
tasks:
  - build: |
      curl -LO  https://nim-lang.org/choosenim/init.sh
      chmod +x init.sh
      ./init.sh -y stable
      PATH=${PATH}:~/.nimble/bin
      cd memex
      nimble install -y
      ./memex build
  - deploy: |
      sshopts="ssh -o StrictHostKeyChecking=no -p 23"
      rsync --rsh="$sshopts" -rvz --progress ./memex/dist xander@metasyn.pw:/var/www/nginx/memex
